const ASP_DATA={
 drugNameMap:{AM:"Ampicillin",AM10:"Ampicillin 10",AN:"Amikacin",C:"Chloramphenicol",CAZ:"Ceftazidime",CC:"Clindamycin",CIP:"Ciprofloxacin",CMZ:"Cefmetazole",CRO:"Ceftriaxone",CTX:"Cefotaxime",DAP:"Daptomycin",DOR:"Doripenem",VRC:"Voriconazole",ETP:"Ertapenem",FEP:"Cefepime",FLO:"Flomoxef",FOX:"Cefoxitin",GM:"Gentamicin",IPM:"Imipenem",LVX:"Levofloxacin",LZD:"Linezolid",MEM:"Meropenem",MEN:"Meropenem",MXF:"Moxifloxacin",MET:"Metronidazole",MI:"Minocycline",OX:"Oxacillin",P:"Penicillin",PIP:"Piperacillin",RA:"Rifampicin",SAM:"Ampicillin/Sulbactam",SFP:"Cefoperazone/Sulbactam",SXT:"Trimethoprim/Sulfamethoxazole",TEC:"Teicoplanin",TGC:"Tigecycline",TZP:"Piperacillin/Tazobactam",VA:"Vancomycin",VAN:"Vancomycin",CL:"Colistin",CFM:"Cefixime",FCT:"FCT",CZ:"Cefazolin",CZA:"Ceftazidime/Avibactam",E:"Erythromycin",STS:"Streptomycin-synergy",G120:"Gentamicin 120",TE:"Tetracycline",CAS:"Caspofungin",FLU:"Fluconazole",FP:"FP",ZA:"ZA"},
 drugDisplay(d,name){let code=this.normalizeDrug(d||"");let nm=this.drugNameMap[code]||name||code;return nm?`${nm} (${code})`:code},
 async loadAll(){const a=ASP_CONFIG.FACT_ASP_MONTHLY_CSV_URL,g=ASP_CONFIG.FACT_ANTIBIOGRAM_CSV_URL;if(!a||a.includes("REPLACE_WITH"))throw new Error("Missing Fact_ASP_Monthly CSV URL in config.js");ASP_UTILS.setStatus("Loading Fact_ASP_Monthly...");ASP_STATE.aspMonthly=this.cleanAsp(ASP_UTILS.parseCSV(await ASP_UTILS.fetchText(a)));if(!ASP_STATE.aspMonthly.length)throw new Error("No valid rows in Fact_ASP_Monthly");
 if(g&&!g.includes("REPLACE_WITH")){ASP_UTILS.setStatus("Loading Fact_Antibiogram_Master...");ASP_STATE.antibiogram=this.cleanAg(ASP_UTILS.parseCSV(await ASP_UTILS.fetchText(g)));if(!ASP_STATE.antibiogram.length)throw new Error("No valid rows in Fact_Antibiogram_Master")}else ASP_STATE.antibiogram=[]},
 cleanAsp(rows){const n=ASP_UTILS.toNum;return rows.map(r=>{let me=n(r.Meropenem_DDD),im=n(r.Imipenem_DDD),et=n(r.Ertapenem_DDD),dor=n(r.Doripenem_DDD),va=n(r.Vancomycin_DDD),tec=n(r.Teicoplanin_DDD);return{...r,YYYYMM:r.YYYYMM||r.Date||"",CRKP_Rate_num:n(r.CRKP_Rate),CRAB_Rate_num:n(r.CRAB_Rate),CRPA_Rate_num:n(r.CRPA_Rate),CREC_Rate_num:n(r.CREC_Rate),MRSA_Rate_num:n(r.MRSA_Rate),VRE_Rate_num:n(r.VRE_Rate),Meropenem_DDD_num:me,Imipenem_DDD_num:im,Ertapenem_DDD_num:et,Doripenem_DDD_num:dor,Vancomycin_DDD_num:va,Teicoplanin_DDD_num:tec,Total_Carbapenem_DDD_num:[me,im,et,dor].filter(x=>x!==null).reduce((a,b)=>a+b,0)}}).filter(r=>r.YYYYMM)},
 cleanAg(rows){return rows.map(r=>{let drug=this.normalizeDrug(r.Drug||"");let org=this.normalizeOrg(r.StandardOrganism||r.Organism||"");let s=ASP_UTILS.toNum(r.SusceptibilityPercent);return{Year:String(r.Year||""),Period:r.Period||"",SourceCategory:r.SourceCategory||"",Organism:org,StandardOrganism:org,ResistancePhenotype:r.ResistancePhenotype||"",Drug:drug,DrugName:this.drugNameMap[drug]||r.DrugName||"",DrugDisplay:this.drugDisplay(drug,this.drugNameMap[drug]||r.DrugName||""),IsolateCount:ASP_UTILS.toNum(r.IsolateCount),SusceptibilityPercent:s,Location:r.Location||"Hospital"}}).filter(r=>r.Year&&r.Period&&r.Organism&&r.Drug&&r.SusceptibilityPercent!==null)},
 normalizeDrug(x){return String(x).trim().toUpperCase()},
 normalizeOrg(x){let s=String(x||"").replace(/^\d+\s*/,"").trim();return s.replace(/Escheric\.?coli/i,"Escherichia coli").replace(/Klebsiel\.?pneumoniae/i,"Klebsiella pneumoniae").replace(/Pseudomo\.?aeruginosa/i,"Pseudomonas aeruginosa").replace(/Acinetob\.?baumannii/i,"Acinetobacter baumannii")}
};
