const ASP_TRENDS={
 classes:{carbapenem:["IPM","MEM","MEN","ETP","DOR"],antiPseudomonalBL:["CAZ","FEP","TZP","PIP"],fluoroquinolone:["CIP","LVX"],aminoglycoside:["AN","GM","GM120"],antiMRSA:["VA","VAN","TEC","LZD","DAP"]},
 init(){this.fillSelectors();this.renderSingleDrugTrend();this.renderDrugClassTrend()},
 fillSelectors(){let orgs=[...new Set(ASP_STATE.antibiogram.map(r=>r.Organism))].sort(),drugs=[...new Set(ASP_STATE.antibiogram.map(r=>r.Drug))].sort();["trendOrganismSelect","classTrendOrganismSelect"].forEach(id=>{let s=document.getElementById(id);s.innerHTML="";orgs.forEach(o=>{let opt=document.createElement("option");opt.value=o;opt.textContent=o;s.appendChild(opt)});if(orgs.includes("Pseudomonas aeruginosa"))s.value="Pseudomonas aeruginosa";else if(orgs.includes("Escherichia coli"))s.value="Escherichia coli"});let ds=document.getElementById("trendDrugSelect");ds.innerHTML="";drugs.forEach(d=>{let opt=document.createElement("option");opt.value=d;opt.textContent=ASP_DATA.drugDisplay(d,"");ds.appendChild(opt)});if(drugs.includes("CRO"))ds.value="CRO"},
 filtered(org,source,drugList){return ASP_STATE.antibiogram.filter(r=>r.Organism===org&&(source==="all"||r.SourceCategory===source)&&(!drugList||drugList.includes(r.Drug)))},
 aggregate(rows){let m={};rows.forEach(r=>{let k=`${r.Year}|${r.Period}`;(m[k]=m[k]||[]).push(r)});return Object.entries(m).map(([k,rs])=>{let [y,p]=k.split("|");return{Year:y,Period:p,label:ASP_UTILS.periodLabel(y,p),order:ASP_UTILS.periodKey(y,p),value:ASP_UTILS.meanWeighted(rs),n:rs.reduce((a,b)=>a+(b.IsolateCount||0),0)}}).sort((a,b)=>a.order-b.order)},
 renderSingleDrugTrend(){let org=document.getElementById("trendOrganismSelect").value,drug=document.getElementById("trendDrugSelect").value,source=document.getElementById("trendSourceSelect").value;let rows=this.filtered(org,source,[drug]);let agg=this.aggregate(rows);ASP_UTILS.renderChart("antibiogramTrendChart",{type:"line",data:{labels:agg.map(x=>x.label),datasets:[{label:`${org} · ${ASP_DATA.drugDisplay(drug,"")}`,data:agg.map(x=>x.value)}]},options:{responsive:true,plugins:{legend:{position:"bottom"},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${ASP_UTILS.fmtPct(c.raw)} · n=${agg[c.dataIndex].n}`}}},scales:{y:{title:{display:true,text:"Susceptibility %"},min:0,max:100}}}});document.getElementById("trendSummary").innerText=`Aggregated ${rows.length} rows into ${agg.length} time points. X-axis is grouped by Year/Period, so repeated labels are removed.`},
 renderDrugClassTrend(){let org=document.getElementById("classTrendOrganismSelect").value,cls=document.getElementById("drugClassSelect").value,source=document.getElementById("classTrendSourceSelect").value,drugs=this.classes[cls]||[];let datasets=drugs.map(d=>{let agg=this.aggregate(this.filtered(org,source,[d]));return{drug:d,agg}}).filter(x=>x.agg.length);let labels=[...new Set(datasets.flatMap(x=>x.agg.map(a=>a.label)))];ASP_UTILS.renderChart("drugClassTrendChart",{type:"line",data:{labels,datasets:datasets.map(x=>({label:ASP_DATA.drugDisplay(x.drug,""),data:labels.map(l=>{let f=x.agg.find(a=>a.label===l);return f?f.value:null})}))},options:{responsive:true,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"bottom"}},scales:{y:{title:{display:true,text:"Susceptibility %"},min:0,max:100}}}})}
};
